export const AUTH_USER = 'AUTH_USER'
export const AUTH_ERROR = 'AUTH_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const LOGOUT_USER = 'LOGOUT_USER'
export const SET_AUTH_USER = 'SET_AUTH_USER'
export const LOADING_START = 'LOADING_START'
export const LOADING_FINISH = 'LOADING_FINISH'
export const UPDATE_USER_ID = 'UPDATE_USER_ID'

export const ADD_BOARD = 'ADD_BOARD'
export const ADD_LIST_TO_BOARD = 'ADD_LIST_TO_BOARD'
export const LOAD_BOARDS = 'LOAD_BOARDS'
export const ADD_TASK_TO_LIST = 'ADD_TASK_TO_LIST'
export const REMOVE_BOARD = 'REMOVE_BOARD'
export const REMOVE_LIST = 'REMOVE_LIST'
export const REMOVE_TASK = 'REMOVE_TASK'
